### PR TITLE
Align repo to template repo

### PR DESCRIPTION
**Pull request by dovholuknf**
Align this repo with the template repo

### CODE REVIEW

**Review by qrkourier — APPROVED** [review]

**Comment by ekoby** [comment]
any reason to change licensing?

**Comment by dovholuknf** [comment]
> any reason to change licensing?

No. it was just a script that ran and copied the defaults. I tried to fix all the ones that I knew/found that were wrong but didn't see this one. i can undo that.

**Comment by ekoby** [comment]
> > any reason to change licensing?
> 
> No. it was just a script that ran and copied the defaults. I tried to fix all the ones that I knew/found that were wrong but didn't see this one. i can undo that.

I'd keep it the way it is

**Comment by dovholuknf** [comment]
> I'd keep it the way it is

which is why i said i'd 'undo' it... :) which i've done. i'll merge this now.

**Pull request merged**
